# Generated by Django 6.0.3 on 2026-03-21 16:55

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPSessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=users.models.get_expiry_time)),
                ('verified', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
