# Generated by Django 6.0.3 on 2026-03-21 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_synced_at', models.DateField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('svg_cache', models.TextField(blank=True, null=True)),
                ('total_active_days', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_activities', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank'), ('codewars', 'CodeWars'), ('github', 'GitHub')], max_length=20)),
                ('activity_date', models.DateField()),
                ('activity_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('generation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.generationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank'), ('codewars', 'CodeWars'), ('github', 'GitHub')], max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('fetch_error', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
