# Generated by Django 6.0.3 on 2026-03-31 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank'), ('github', 'GitHub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank'), ('github', 'GitHub')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('platform', 'activity_date')},
        ),
        migrations.AlterUniqueTogether(
            name='platformaccount',
            unique_together={('user', 'platform')},
        ),
    ]
