# Generated by Django 6.0.3 on 2026-04-23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_alter_activity_platform_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together={("generation_request", "platform", "activity_date")},
        ),
    ]

