# Generated by Django 6.0.3 on 2026-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
