# Generated by Django 6.0.3 on 2026-07-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_platformaccount_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetrics',
            name='easy_questions_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermetrics',
            name='hard_questions_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermetrics',
            name='medium_questions_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermetrics',
            name='total_contests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermetrics',
            name='total_questions_solved',
            field=models.IntegerField(default=0),
        ),
    ]
