# Generated by Django 6.0.3 on 2026-07-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_usermetrics_easy_questions_solved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank'), ('github', 'GitHub'), ('geeksforgeeks', 'GeeksForGeeks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank'), ('github', 'GitHub'), ('geeksforgeeks', 'GeeksForGeeks')], max_length=20),
        ),
    ]
