# Generated by Django 6.0.3 on 2026-07-12 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
